### ISSUE TITLE
Is there any reason to pinpoint fastapi dependency ?

### ISSUE THREAD

**Issue by potens1** [jtom38/fastapi_healthcheck#21]
Hi,

Is there any reason to pinpoint fastapi dependency in the package released on pypi ?

I understood you would like to validate it again when fastapi 1.0.0 is released, but, then, why not using 
```
"fastapi < 1.0.0"
```
Into "pyproject.toml".

This way, you will get bug reports only if something is broken with some version of fastapi (until 1.0.0), because right now, you will have to release a new version of the package to bump the deps to follow exactly fastapi's versions.
(I mean, this "issue" could have been named "Please bump version", and then you will get a lot of those for each fastapi revision, even if nothing broke)
Maybe you want to ensure it is working for each fastapi version (and that's a valid reason, this "issue" is a real question)

The source of this is
```
 Because fastapi-healthcheck (0.2.7) depends on fastapi (>=0.82.0,<0.83.0)
   and youshinypackage depends on fastapi (^0.85.0), fastapi-healthcheck is forbidden.
  So, because firmware depends on fastapi-healthcheck (0.2.7), version solving failed.
```

Thanks a lot for your package !

**Comment by jtom38** [comment]
The fastapi version should go up to 1.0.0.  That is just to make sure if anything changes it can be reviewed for breaking changes.

Starlette was missed, so thank you @paulvaneijden for your PR, it was approved and merged.  I will get a new release out to correct the issue.

**Comment by jtom38** [comment]
v0.2.8 was released to address this issue.

https://pypi.org/project/fastapi-healthcheck/0.2.8/

**Comment by paulvaneijden** [comment]
I opened a PR to remedy this #23
