### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Marie59** [jtom38/fastapi_healthcheck#28]
Hi ! I would like to add fastapi_healthcheck to conda but I need a license file to do so. Could you add one ?
Thanks

**Comment by jtom38** [comment]
Hello @Marie59 

I have added this to my list and will add one soon. I'm about to go on holiday and will be busy till the new year.

**Comment by Marie59** [comment]
Thank you and happy holiday !

**Comment by jtom38** [comment]
@Marie59 

As of v0.2.12 the package has the MIT license.  This change also shows up on pypi. 

https://pypi.org/project/fastapi-healthcheck/

**Comment by Marie59** [comment]
Perfect ! Thanks a lot !
