### ISSUE TITLE
Please support newer versions of FastAPI

### ISSUE THREAD

**Issue by wavermartijn** [jtom38/fastapi_healthcheck#7]
I like the module, but unfortunately it only works with FastAPI 0.70-0.71 Would be nice when the latest versions are supported as well

**Comment by jtom38** [comment]
Thanks for the feedback @wavermartijn.  I will take a look at getting the package to support newer versions.  If you have a PR you would l like to submit, sent it over.

**Comment by jtom38** [comment]
@wavermartijn I did push an update that I think should let newer version of FastAPI work with the module.  I haven't tested it yet due to time.

**Comment by y-mironov** [comment]
Hi.
Can you update your project dependencies and rebuild package ?  
https://python-poetry.org/docs/basic-usage/#updating-dependencies-to-their-latest-versions
Now I can't install fastapi-healthcheck without pain.

**Comment by jtom38** [comment]
Let me take a look and see what I can do. I will see about getting a github action to build the project once a week if I can to avoid this problem going forward.

**Comment by panosangelopoulos** [comment]
@jtom38 Perhaps we can close this issue since we updated the requirements. Wdyt?

**Comment by jtom38** [comment]
@panosangelopoulos I think with this PR we can close it. https://github.com/jtom38/fastapi_healthcheck/pull/17

That change should let the package continue to be used with newer versions of FastAPI till it hits v1.0.0.  At that point a review of FastAPI will be needed again to validate that the package still works or if it needs any updates.

**Comment by panosangelopoulos** [comment]
@jtom38 It makes sense! I just approved your PR #17 .

**Comment by jtom38** [comment]
https://github.com/jtom38/fastapi_healthcheck/releases/tag/v0.2.6 was released and this should work with newer versions of FastAPI until v1.0.0.  At that time, the package will need to be validated to make sure its working as expected.

**Comment by jtom38** [comment]
Correction.  Please use https://github.com/jtom38/fastapi_healthcheck/releases/tag/v0.2.7 or newer as v.0.2.6 didn't generate a package.

https://pypi.org/project/fastapi-healthcheck/0.2.7/
